
services:
  # 1. The Agent Container (Python)
  agent:
    build:
      context: ./agent
    container_name: rl_firewall_agent
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true
    network_mode: "host"
    environment:
      - REDIS_HOST=127.0.0.1 # Using host networking
    depends_on:
      - redis
      - backend

  # 2. The Application Container (PHP-FPM / Laravel)
  backend:
    build:
      context: ./backend
    container_name: rl_firewall_backend
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - REDIS_HOST=redis
      - BROADCAST_DRIVER=reverb
      - REVERB_APP_ID=683668
      - REVERB_APP_KEY=firewallkey123
      - REVERB_APP_SECRET=firewallsecret
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/var/www/html # Mount source code for easy updates

  # 3. The Web Server Container (Nginx / Vue.js)
  webserver:
    build:
      context: ./frontend
      network: host
    container_name: rl_firewall_web
    ports:
      - "80:80"
    depends_on:
      - backend

  # 4. State Container (MySQL)
  db:
    image: mysql:8.0
    container_name: rl_firewall_db
    environment:
      - MYSQL_DATABASE=firewall_telemetry
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  # 5. Broker Container (Redis)
  redis:
    image: redis:alpine
    container_name: rl_firewall_redis
    ports:
      - "6379:6379"

volumes:
  db_data: